#!/bin/bash

echo "================================================================================"
echo "🚀 HUGGING FACE DEPLOYMENT HELPER"
echo "================================================================================"
echo ""
echo "Your files are ready and committed!"
echo ""
echo "================================================================================"
echo "OPTION 1: Push with Token"
echo "================================================================================"
echo ""
echo "1. Get token: https://huggingface.co/settings/tokens"
echo "2. Click 'New token' → Select 'write' role → Generate"
echo "3. Copy the token (starts with hf_...)"
echo ""
echo "4. Run this command (replace YOUR_TOKEN):"
echo ""
echo "   git push https://Hammaf3213:YOUR_TOKEN@huggingface.co/spaces/Hammaf3213/youtube master"
echo ""
echo "================================================================================"
echo "OPTION 2: Manual Upload (Easier!)"
echo "================================================================================"
echo ""
echo "1. Open: https://huggingface.co/spaces/Hammaf3213/youtube"
echo "2. Click 'Add file' → 'Upload files'"
echo "3. Drag these files:"
echo "   - Dockerfile"
echo "   - requirements.txt"
echo "   - README.md"
echo "   - integrated_app.py"
echo "   - .dockerignore"
echo "   - yt2tik/ folder"
echo "   - templates/ folder"
echo "4. Click 'Commit to main'"
echo ""
echo "================================================================================"
echo "AFTER UPLOAD"
echo "================================================================================"
echo ""
echo "1. Build will start automatically (~10 minutes)"
echo "2. Add environment variables in Settings:"
echo "   YOUTUBE_API_KEY = your_youtube_api_key"
echo "   FLASK_SECRET_KEY = any_random_string"
echo ""
echo "3. Your app will be live at:"
echo "   https://hammaf3213-youtube.hf.space"
echo ""
echo "================================================================================"
echo ""
echo "Files location: $(pwd)"
echo ""
echo "Ready to upload! Choose Option 1 or 2 above."
echo ""
